Vicwur/develop forcing
wietsefranssen/VIC pull request #12
Opened 2018-04-11 12:33 UTC by BramDr

Change the **forcing input file system** to allow a different forcing files per forcing variable. Also the second forcing file previously implemented in VIC is removed since these forcing variables can now be given a new forcing file.

Forcing in the global parameter file should now be specified as follows:
# FORCE_TYPE	TYPE			VARIABLE NAME		FILE
FORCE_TYPE    	AIR_TEMP		tas					forcing/filename.
If necessary forcing files are not given, vic will exit with an error. Forcing is read in per file in vic_force.

There are still redundant structures and variables allocated to do with the old forcing file system (specifically param_set_struct and force_type_struct), which can be removed in the future

2018-04-19 10:19 UTC, wietsefranssen requested changes

2018-04-19 10:19 UTC, wietsefranssen commented on vic/include/vic_general.h
> +    unsigned short int FORCE_ENDIAN[N_FORCING_TYPES];  /**< endian-ness of input file, used for
Please Remove FORCE_ENDIAN, etc

2018-04-20 15:25 UTC, BramDr commented
Included the requested changes and some more updates. Ready for pull... (do I need to open a new pull request?)

2018-04-23 11:23 UTC, wietsefranssen approved these changes
Looks good!
Also thanks for removing blank lines and spaces

2018-04-23 11:23 UTC, merged