Vicwur/develop logging
wietsefranssen/VIC pull request #13
Opened 2018-04-16 06:56 UTC by BramDr

**Update to 2 errors and warnings.**
1. Previously when the linked list could not find an entry it returned **999**. This return is then often used as an array-index which caused a segmentation fault. Now when the linked list cannot find an entry it returns an **error**, clearly indicating what variable could not be found.
2. Previously when a defined output in the global parameter file could not be located (for example: a plugin was not activated but the output was asked), VIC gave an **error and exited**. This caused some minor inconveniences. Now VIC only gives a **warning and removes the requested output** from the output stream.

2018-04-19 10:28 UTC, wietsefranssen requested changes

2018-04-19 10:28 UTC, wietsefranssen commented on vic/src/vicwur/main_functions/vic_init_output.c
> +    for (j = 0; j < stream->nvars; j++) {
Please remove all black parts

2018-04-20 15:26 UTC, BramDr commented
Included the requested changes. Ready for pull... (do I need to open a new pull request?)

2018-04-23 11:18 UTC, wietsefranssen approved these changes

2018-04-23 11:19 UTC, merged

2018-04-23 11:20 UTC, wietsefranssen commented
No you don't need to open a new pull request